### ISSUE TITLE
Chart Does not Create DaemonSet on Kubernetes 1.16+

### ISSUE THREAD

**Issue by kengibous** [Panopta/kubernetes#1]
I believe the chart is using an old api reference -

https://github.com/Panopta/kubernetes/blob/master/panopta/templates/agent.yaml

shows:
apiVersion: extensions/v1beta1

but kubernetes api documentation:
https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#daemonset-v1-apps

apiVersion: apps/v1

Probably better to have this as a variable or something to support various kubernetes versions

**Comment by KeithScheiwiller** [comment]
Fixed in chart version 0.1.9

Switched to `apps/v1` for DaemonSet which should be available since Kubernetes 1.9

Thanks for the report!
