### ISSUE TITLE
panopta-k8s-agent logs "configmaps \"panopta-configmap\" not found"

### ISSUE THREAD

**Issue by kengibous** [Panopta/kubernetes#3]
I am seeing this message displayed from the panopta-k8s-agent daemonset

```
Setting up python-pysqlite2 (2.7.0-1) ...
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "configmaps \"panopta-configmap\" not found",
  "reason": "NotFound",
  "details": {
    "name": "panopta-configmap",
    "kind": "configmaps"
  },
  "code": 404
```

However I do have a panopta-configmap object

```
kubectl get configmaps -n panopta                 
NAME                DATA   AGE
panopta-configmap   6      29m
panopta.v1          1      29m
```

**Comment by KeithScheiwiller** [comment]
Addressed in v0.1.12. The agent will now know to look for the configmap in the namespace it was installed in.

Note that if you're utilizing this chart to install kube-state-metrics, you'll need to also update `kubeStateMetrics.endpoint` in `values.yaml` for the proper namespace.
e.g.
`http://kube-state-metrics.panopta.svc:8080`
